jwt:
  tokenHeader: auth-token #JWT存储的请求头
  secure: ZAQ!xsw2
  expire: 300000
  tokenHead: Bearer #JWT负载中拿到开头
secure:
  ignore:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /register
      - /login
      - /api/resource

role:
  name: regular
  code: regular
  description: 普通用户

authority:
  mybatisAuthoritySettings:
    -
      authorityCode: TEST_AUTHORITY
      columnConstraints:
        -
          columnName: state
          operation: EQUAL
          constraints: "'state3'"
